Drop TABLE IF EXISTS users;
CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR(15) NOT NULL,
email VARCHAR(30) UNIQUE NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
phone VARCHAR(50) NOT NULL,
city VARCHAR(110) NOT NULL
)DEFAULT CHARSET=utf8;
commit;